plugins { id 'com.android.application' }
android {
    namespace 'icu.yunzhan.panel'
    compileSdk 36
    defaultConfig {
        applicationId 'icu.yunzhan.panel'
        minSdk 30
        targetSdk 36
        versionCode 130
        versionName '1.3.0'
        testInstrumentationRunner 'android.test.InstrumentationTestRunner'
    }
    buildFeatures { buildConfig true }
    buildTypes {
        debug { applicationIdSuffix '.qa' }
        release { minifyEnabled false }
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
dependencies { testImplementation 'junit:junit:4.13.2' }
