import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const load=async name=>JSON.parse(await readFile(new URL(name,import.meta.url),'utf8'));
test('Apache identity policies require explicit trust and do not claim unverified commercial parity',async()=>{
 const [registry,contracts]=await Promise.all([load('../registry/apps.json'),load('../registry/functional-contracts.json')]);
 const manifest=registry.apps.find(a=>a.id==='apache-waf'),contract=contracts.apps.find(a=>a.id===manifest.id);
 assert.equal(manifest.version,'2.2.0');
 assert(manifest.capabilities.some(s=>s.includes('默认关闭')&&s.includes('CIDR')));
 assert(manifest.capabilities.some(s=>s.includes('原始连接 IP')));
 assert(manifest.capabilities.some(s=>s.includes('普通保存不隐式升级')));
 assert(manifest.capabilities.some(s=>s.includes('三文件持久恢复事务')&&s.includes('UID/GID')));
 assert(manifest.capabilities.some(s=>s.includes('未确认恢复不清除事务')));
 assert(contract.scenarios.some(s=>s.includes('两种架构各 29 次')));
 assert(contract.scenarios.some(s=>s.includes('真实 SIGKILL 子进程')&&s.includes('四个提交截点')));
 assert(contract.boundaries.some(s=>s.includes('仅服务 inactive/failed')&&s.includes('MainPID')));
 assert(contract.boundaries.some(s=>s.includes('不等于正式签名执行服务')));
 assert(contract.boundaries.some(s=>s.includes('23r26a')&&s.includes('GET 返回 503')&&s.includes('失败证据保留')));
 assert(contract.gaps.some(s=>s.includes('100 份')&&s.includes('归档界面')));
 assert(contract.scenarios.some(s=>s.includes('未可信对端')&&s.includes('IPv6')));
 assert(contract.scenarios.some(s=>s.includes('缺失指纹')&&s.includes('FIFO')));
 assert(contract.boundaries.some(s=>s.includes('未签名冻结测试')&&s.includes('签名面板')));
 assert(contract.boundaries.some(s=>s.includes('RemoteIPHeader')&&s.includes('可信对端名单')));
 assert(contract.boundaries.some(s=>s.includes('原版 1.0')&&s.includes('固定规则摘要')&&s.includes('HEAD')));
 assert(contract.boundaries.some(s=>s.includes('23r25c')&&s.includes('失败任务')));
 assert(contract.gaps.some(s=>s.includes('完整请求体')&&s.includes('CC')));
 assert(contract.gaps.some(s=>s.includes('完整五种系统')));
 assert.equal(contracts.commercial_feature_parity_complete,false);
});
test('ordinary Nginx log recovery keeps unknown outcomes and remaining compatibility gaps explicit',async()=>{
 const contracts=await load('../registry/functional-contracts.json');
 const app=contracts.apps.find(a=>a.id==='nginx');
 assert(app.scenarios.some(s=>s.includes('USR1')));
 assert(app.scenarios.some(s=>s.includes('SIGKILL')&&s.includes('未知')));
 assert(app.scenarios.some(s=>s.includes('只追加证据')&&s.includes('不伪造')));
 assert(app.boundaries.some(s=>s.includes('内核写保护')));
 assert(app.boundaries.some(s=>s.includes('不伪造 Nginx')));
 assert(app.gaps.some(s=>s.includes('Debian 12')&&s.includes('Ubuntu 26')));
 assert(app.gaps.some(s=>s.includes('窄视口')));
 assert.equal(contracts.commercial_feature_parity_complete,false);
});
test('all 50 applications have business scenarios, not install-only acceptance',async()=>{
 const [registry,contracts]=await Promise.all([load('../registry/apps.json'),load('../registry/functional-contracts.json')]);
 assert.equal(contracts.commercial_feature_parity_complete,false);
 assert.equal(contracts.apps.length,50);
 assert.deepEqual(contracts.apps.map(a=>a.id).sort(),registry.apps.map(a=>a.id).sort());
 for(const app of contracts.apps){assert.ok(app.scenarios.length>=3,app.id);assert.ok(app.scenarios.every(s=>s.length>=4),app.id)}
 for(const id of ['website-analytics','files-sync','php-code-security','enterprise-tamper-proof'])assert.ok(contracts.apps.find(a=>a.id===id).gaps.length>0,id);
});
test('published manifest OS values are permitted by the schema',async()=>{
 const [registry,schema]=await Promise.all([load('../registry/apps.json'),load('../schema/app.schema.json')]);
 const systems=schema.properties.compatibility.properties.os.items.enum;
 for(const app of registry.apps)for(const os of app.compatibility.os)assert.ok(systems.includes(os),app.id+' '+os);
});
test('daily SMTP publishes independent version and truthful transport/security boundaries',async()=>{
 const [registry,contracts]=await Promise.all([load('../registry/apps.json'),load('../registry/functional-contracts.json')]);
 const manifest=registry.apps.find(a=>a.id==='daily-report'),contract=contracts.apps.find(a=>a.id===manifest.id);
 assert.equal(manifest.version,'1.4.0');
 assert(manifest.capabilities.some(s=>s.includes('TLS/STARTTLS SMTP')));
 assert.match(manifest.summary,/250.*中继接收/);
 assert(contract.scenarios.some(s=>s.includes('AUTH/DATA')));
 assert(contract.scenarios.some(s=>s.includes('Message-ID')&&s.includes('新 PID')));
 assert(contract.scenarios.some(s=>s.includes('旧 URL/Secret')));
 assert(contract.boundaries.some(s=>s.includes('不保证最终收件箱')&&s.includes('恰好一次')));
 assert(contract.boundaries.some(s=>s.includes('默认关闭')));
 assert(contract.boundaries.some(s=>s.includes('1–5')&&s.includes('SMTPUTF8')));
 assert(contract.boundaries.some(s=>s.includes('旧核心拒绝未来应用版本')));
 assert(contract.gaps.some(s=>s.includes('邮件账号')));
 assert(contract.scenarios.some(s=>s.includes('Debian 13 amd64')&&s.includes('Ubuntu 24.04 arm64')&&s.includes('CUA')));
 assert(contract.scenarios.some(s=>s.includes('1.3.1 到 1.4.0')&&s.includes('幂等键')&&s.includes('标记清除')));
 assert(!contract.gaps.some(s=>s.includes('界面验收尚待完成')));
 assert(contract.boundaries.some(s=>s.includes('首次 x86_64 QA')&&s.includes('失败证据保留')));
 assert(contract.boundaries.some(s=>s.includes('临时数据库')&&s.includes('公网收件箱')));
 assert.equal(contracts.commercial_feature_parity_complete,false);
});
test('body WAF and analytics additions keep truthful limits and independent versions',async()=>{
 const [registry,contracts]=await Promise.all([load('../registry/apps.json'),load('../registry/functional-contracts.json')]);
 const waf=registry.apps.find(a=>a.id==='nginx-waf'),analytics=registry.apps.find(a=>a.id==='website-analytics');
 assert.equal(waf.version,'2.5.1');assert.equal(analytics.version,'2.3.0');
 assert.match(waf.summary,/默认不启用/);assert(!waf.summary.includes('不含完整请求体检测'));
 assert(analytics.capabilities.some(s=>s.includes('INP'))&&analytics.capabilities.some(s=>s.includes('转化漏斗')));
 assert(analytics.capabilities.some(s=>s.includes('HTML 自动接入')&&s.includes('默认关闭')));
 assert(analytics.capabilities.some(s=>s.includes('ABI'))&&analytics.capabilities.some(s=>s.includes('工作进程')));
 assert.match(analytics.summary,/默认关闭/);assert.match(analytics.summary,/CSP/);
 const w=contracts.apps.find(a=>a.id===waf.id),a=contracts.apps.find(a=>a.id===analytics.id);
 assert(w.scenarios.some(s=>s.includes('SIGKILL')));
 assert(waf.capabilities.some(s=>s.includes('旧工作进程')));
 assert(waf.capabilities.some(s=>s.includes('可信代理 CIDR')));
 assert(waf.capabilities.some(s=>s.includes('CC 观察计数')));
 assert(waf.capabilities.some(s=>s.includes('拒绝接管外部限速')));
 assert(w.scenarios.some(s=>s.includes('未可信对端')));
 assert(w.scenarios.some(s=>s.includes('96 个单次 GET')));
 assert(w.scenarios.some(s=>s.includes('不运行 APT')));
 assert(w.scenarios.some(s=>s.includes('128 次真实业务请求')));
 assert(w.scenarios.some(s=>s.includes('14 条 200 模拟拒绝')));
 assert(w.scenarios.some(s=>s.includes('58 个受管网站')));
 assert(!w.gaps.some(s=>s.includes('观察模式不执行')));
 assert(!w.gaps.some(s=>s.includes('可信反代来源的签名实装')));
 assert(!w.gaps.some(s=>s.includes('请求体引擎同时启用')));
 assert(w.boundaries.some(s=>s.includes('不自动导入 CDN')));
 assert(w.boundaries.some(s=>s.includes('不是 HTTP 请求数')));
 assert(waf.capabilities.some(s=>s.includes('自动轮转')));
 assert(waf.capabilities.some(s=>s.includes('保留期')&&s.includes('不处理当前日志')));
 assert(waf.capabilities.some(s=>s.includes('未知删除结果')&&s.includes('不重试')));
 assert(waf.capabilities.some(s=>s.includes('UID/GID')&&s.includes('拒绝猜测')));
 assert(w.boundaries.some(s=>s.includes('2.5 保留期')&&s.includes('默认关闭')));
 assert(w.boundaries.some(s=>s.includes('未知结果改成成功')&&s.includes('不将')));
 assert(w.boundaries.some(s=>s.includes('实际经过三十天')));
 assert(w.gaps.some(s=>s.includes('2.5.1 完整五种系统')&&s.includes('仍待完成')));
 assert(w.scenarios.some(s=>s.includes('纳秒整数')&&s.includes('失败证据保留')));
 assert(w.scenarios.some(s=>s.includes('真实签名分钟执行器')&&s.includes('下一分钟不得重选')));
 assert(w.scenarios.some(s=>s.includes('23r24d 与 23r24e')&&s.includes('整机不同 boot ID')));
 assert(w.scenarios.some(s=>s.includes('库存待核对而不是零份')&&s.includes('下载文件落盘尚未验收')));
 assert(w.scenarios.some(s=>s.includes('第一份移除后')&&s.includes('新计划')));
 assert(w.boundaries.some(s=>s.includes('64 位整数')&&s.includes('全库存')));
 assert(w.boundaries.some(s=>s.includes('2.5.0')&&s.includes('复现失败')));
 assert(w.boundaries.some(s=>s.includes('原快照或索引')&&s.includes('继续暂停')));
 assert(waf.capabilities.some(s=>s.includes('当前与历史计划')&&s.includes('不重试')));
 assert(w.scenarios.some(s=>s.includes('独立新 PID')));
 assert(w.scenarios.some(s=>s.includes('同长度快照篡改')));
 assert(w.scenarios.some(s=>s.includes('专用固定依赖进程')));
 assert(w.scenarios.some(s=>s.includes('三个阶段均单路')&&s.includes('1 GiB')));
 assert(w.boundaries.some(s=>s.includes('640 MiB')&&s.includes('不是连续峰值')));
 assert(w.boundaries.some(s=>s.includes('不自动增大内存上限')));
 assert(w.boundaries.some(s=>s.includes('32 MiB'))&&w.gaps.some(s=>s.includes('普通访问/错误日志')));
 assert(!w.gaps.some(s=>s.includes('签名实装 API')));
 assert(w.scenarios.some(s=>s.includes('整机冷启动')&&s.includes('可信 IPv6')));
 assert(w.scenarios.some(s=>s.includes('从三份变为四份')&&s.includes('草稿')));
 assert(w.boundaries.some(s=>s.includes('不覆盖未保存')));
 assert(a.boundaries.some(s=>s.includes('20000'))&&a.gaps.some(s=>s.includes('SPA 独立路由性能')));
 assert(!a.gaps.some(s=>s.includes('INP')));
 assert(a.scenarios.some(s=>s.includes('23r27b')&&s.includes('生产构建服务')));
 assert(a.scenarios.some(s=>s.includes('两种架构实际浏览器')&&s.includes('DOM 标识')));
 assert(a.scenarios.some(s=>s.includes('Unix 路径异常')&&s.includes('404')));
 assert(!a.gaps.some(s=>s.includes('完整双架构 API/服务/浏览器与冷启动')));
 assert(a.gaps.some(s=>s.includes('完整五种系统')&&s.includes('窄视口')));
 assert(a.boundaries.some(s=>s.includes('1.18')&&s.includes('不自动替换')));
 assert(a.boundaries.some(s=>s.includes('交互页截图')&&s.includes('不冒充')));
 assert(a.scenarios.some(s=>s.includes('19100 实际签名目录')&&s.includes('更新标记清除')));
 assert(a.scenarios.some(s=>s.includes('1315 份配置身份')&&s.includes('统计事件')));
 assert(a.boundaries.some(s=>s.includes('purpose')&&s.includes('不重复提交')));
 assert.equal(contracts.commercial_feature_parity_complete,false);
});
test('load balancing publishes explicitly authorized active health routing without claiming L4 or all distributions',async()=>{
 const [registry,contracts]=await Promise.all([load('../registry/apps.json'),load('../registry/functional-contracts.json')]);
 const manifest=registry.apps.find(a=>a.id==='load-balance'),contract=contracts.apps.find(a=>a.id===manifest.id);
 assert.equal(manifest.version,'1.8.1');
 assert(manifest.capabilities.some(s=>s.includes('修订')));
 assert(contract.scenarios.some(s=>s.includes('ABA')));
 assert(contract.scenarios.some(s=>s.includes('冷启动')));
 assert(contract.scenarios.some(s=>s.includes('两文件')));
 assert(contract.boundaries.some(s=>s.includes('127.0.0.1')));
 assert(contract.boundaries.some(s=>s.includes('512')));
 assert(contract.boundaries.some(s=>s.includes('不代表 HTTP')));
 assert(contract.gaps.some(s=>s.includes('TCP/UDP')));
 assert(manifest.capabilities.some(s=>s.includes('持续 HTTP')));
 assert(contract.scenarios.some(s=>s.includes('后台持续 HTTP')));
 assert(contract.scenarios.some(s=>s.includes('实际更新清单')));
 assert(contract.scenarios.some(s=>s.includes('节点数组')));
 assert(contract.boundaries.some(s=>s.includes('32 个节点')));
 assert(contract.boundaries.some(s=>s.includes('只观测')));
 assert(contract.gaps.some(s=>s.includes('外部告警')));
 assert(manifest.capabilities.some(s=>s.includes('全故障不放行')));
 assert(contract.scenarios.some(s=>s.includes('各 34 项 Linux 回归无跳过')));
 assert(contract.scenarios.some(s=>s.includes('三个真实 SIGKILL')&&s.includes('四文件')));
 assert(contract.scenarios.some(s=>s.includes('ENABLE HEALTH ROUTING')));
 assert(contract.boundaries.some(s=>s.includes('默认只观测')&&s.includes('1.7.0')));
 assert(contract.boundaries.some(s=>s.includes('其他发行版不等同')));
 assert(contract.boundaries.some(s=>s.includes('运行序列单独递增')));
 assert(manifest.capabilities.some(s=>s.includes('入口专用 CA')));
 assert(contract.scenarios.some(s=>s.includes('错误域名')&&s.includes('过期证书')));
 assert(contract.boundaries.some(s=>s.includes('独立固定 IP 端口')&&s.includes('禁止私钥')));
 assert(manifest.capabilities.some(s=>s.includes('HTTPS 后端转发')));
 assert(contract.scenarios.some(s=>s.includes('三文件')&&s.includes('六个摘要')));
 assert(contract.boundaries.some(s=>s.includes('不使用系统根')&&s.includes('HTTP 降级')));
 assert(!contract.gaps.some(s=>s.includes('三文件整机冷启动验收仍待完成')));
 assert(contract.scenarios.some(s=>s.includes('真实签名执行器各 44 次')));
 assert(contract.scenarios.some(s=>s.includes('正式签名 Nginx')&&s.includes('三文件事务')));
 assert(contract.scenarios.some(s=>s.includes('修订 6 到 7')&&s.includes('冷启动')));
 assert.equal(contracts.commercial_feature_parity_complete,false);
});
