import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const load=async name=>JSON.parse(await readFile(new URL(name,import.meta.url),'utf8'));
test('all 50 applications have business scenarios, not install-only acceptance',async()=>{
 const [registry,contracts]=await Promise.all([load('../registry/apps.json'),load('../registry/functional-contracts.json')]);
 assert.equal(contracts.commercial_feature_parity_complete,false);
 assert.equal(contracts.apps.length,50);
 assert.deepEqual(contracts.apps.map(a=>a.id).sort(),registry.apps.map(a=>a.id).sort());
 for(const app of contracts.apps){assert.ok(app.scenarios.length>=3,app.id);assert.ok(app.scenarios.every(s=>s.length>=4),app.id)}
 for(const id of ['website-analytics','files-sync','php-code-security','enterprise-tamper-proof'])assert.ok(contracts.apps.find(a=>a.id===id).gaps.length>0,id);
});
test('published manifest OS values are permitted by the schema',async()=>{
 const [registry,schema]=await Promise.all([load('../registry/apps.json'),load('../schema/app.schema.json')]);
 const systems=schema.properties.compatibility.properties.os.items.enum;
 for(const app of registry.apps)for(const os of app.compatibility.os)assert.ok(systems.includes(os),app.id+' '+os);
});
test('body WAF and analytics additions keep truthful limits and independent versions',async()=>{
 const [registry,contracts]=await Promise.all([load('../registry/apps.json'),load('../registry/functional-contracts.json')]);
 const waf=registry.apps.find(a=>a.id==='nginx-waf'),analytics=registry.apps.find(a=>a.id==='website-analytics');
 assert.equal(waf.version,'2.2.0');assert.equal(analytics.version,'2.2.0');
 assert.match(waf.summary,/显式构建与启用/);assert(!waf.summary.includes('不含完整请求体检测'));
 assert(analytics.capabilities.some(s=>s.includes('INP'))&&analytics.capabilities.some(s=>s.includes('转化漏斗')));
 const w=contracts.apps.find(a=>a.id===waf.id),a=contracts.apps.find(a=>a.id===analytics.id);
 assert(w.scenarios.some(s=>s.includes('SIGKILL')));
 assert(waf.capabilities.some(s=>s.includes('旧工作进程')));
 assert(waf.capabilities.some(s=>s.includes('可信代理 CIDR')));
 assert(w.scenarios.some(s=>s.includes('未可信对端')));
 assert(w.boundaries.some(s=>s.includes('不自动导入 CDN')));
 assert(w.boundaries.some(s=>s.includes('不是 HTTP 请求数')));
 assert(w.boundaries.some(s=>s.includes('32 MiB'))&&w.gaps.some(s=>s.includes('调度')));
 assert(a.boundaries.some(s=>s.includes('20000'))&&a.gaps.some(s=>s.includes('SPA 独立路由性能')));
 assert(!a.gaps.some(s=>s.includes('INP')));
 assert.equal(contracts.commercial_feature_parity_complete,false);
});
test('load balancing publishes bounded HTTP observations and recovery without claiming L4 or active traffic mutation',async()=>{
 const [registry,contracts]=await Promise.all([load('../registry/apps.json'),load('../registry/functional-contracts.json')]);
 const manifest=registry.apps.find(a=>a.id==='load-balance'),contract=contracts.apps.find(a=>a.id===manifest.id);
 assert.equal(manifest.version,'1.5.0');
 assert(manifest.capabilities.some(s=>s.includes('修订')));
 assert(contract.scenarios.some(s=>s.includes('ABA')));
 assert(contract.scenarios.some(s=>s.includes('冷启动')));
 assert(contract.scenarios.some(s=>s.includes('两文件')));
 assert(contract.boundaries.some(s=>s.includes('127.0.0.1')));
 assert(contract.boundaries.some(s=>s.includes('512')));
 assert(contract.boundaries.some(s=>s.includes('不代表 HTTP')));
 assert(contract.gaps.some(s=>s.includes('TCP/UDP')));
 assert(manifest.capabilities.some(s=>s.includes('持续 HTTP')));
 assert(contract.scenarios.some(s=>s.includes('后台持续 HTTP')));
 assert(contract.scenarios.some(s=>s.includes('实际更新清单')));
 assert(contract.scenarios.some(s=>s.includes('节点数组')));
 assert(contract.boundaries.some(s=>s.includes('32 个节点')));
 assert(contract.boundaries.some(s=>s.includes('只观测')));
 assert(contract.gaps.some(s=>s.includes('摘除')));
 assert(manifest.capabilities.some(s=>s.includes('入口专用 CA')));
 assert(contract.scenarios.some(s=>s.includes('错误域名')&&s.includes('过期证书')));
 assert(contract.boundaries.some(s=>s.includes('独立固定 IP 端口')&&s.includes('禁止私钥')));
 assert(contract.gaps.some(s=>s.includes('后端业务转发')));
 assert.equal(contracts.commercial_feature_parity_complete,false);
});
