[Service]
ExecStartPre=
ExecStartPre=/opt/panel/bin/panel-executor --nginx-operation test
ExecStart=
ExecStart=/opt/panel/bin/panel-executor --nginx-operation start
ExecReload=
ExecReload=/opt/panel/bin/panel-executor --nginx-operation reload
PIDFile=/run/panel-nginx/nginx.pid
RuntimeDirectory=panel-nginx
RuntimeDirectoryMode=0755
RuntimeDirectoryPreserve=yes
ExecStop=
ExecStop=/sbin/start-stop-daemon --stop --quiet --retry QUIT/5 --pidfile /run/panel-nginx/nginx.pid
