#!/usr/bin/env bash
set -euo pipefail
DIR="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
[[ -f "$DIR/RELEASE" && -f "$DIR/SHA256SUMS" ]] || { echo 'release metadata missing' >&2; exit 1; }
# RELEASE is generated by our packager. Validate every value before sourcing it.
while IFS='=' read -r key value; do
  case "$key" in
    PANEL_FORMAT) [[ "$value" == 1 ]] ;;
    PANEL_VERSION) [[ "$value" =~ ^[0-9]+\.[0-9]+\.[0-9]+([.-][a-z0-9]+)*$ ]] ;;
    PANEL_OS) [[ "$value" == linux ]] ;;
    PANEL_ARCH) [[ "$value" == amd64 || "$value" == arm64 ]] ;;
    *) false ;;
  esac || { echo "invalid release field: $key" >&2; exit 1; }
done < "$DIR/RELEASE"
(cd "$DIR" && if command -v sha256sum >/dev/null; then sha256sum -c SHA256SUMS >/dev/null; else shasum -a 256 -c SHA256SUMS >/dev/null; fi)
python3 "$DIR/release-file-modes.py" check "$DIR"
echo 'release checksums verified'
